### ISSUE TITLE
Travis Integration & Build status badge

### ISSUE THREAD

**Issue by phxql** [qaware/heimdall#3]
Add Travis Integration and a build status badge to the readme.

**Comment by phxql** [comment]
Also add coveralls coverage badge. There is a user contributed plugin here: https://github.com/trautonen/coveralls-maven-plugin and a blog post about it: http://blog.eluder.org/2013/06/code-coverage-for-github-hosted-java-projects-with-coveralls/

**Comment by phxql** [comment]
Added Travis CI and a build badge.

**Comment by lreimer** [comment]
And what about the coveralls coverage badge? Not working?

**Comment by phxql** [comment]
Requests permission for read/write access on all repositories (even the private ones from QAware), have to talk to Josef A. if that's ok.
