### ISSUE TITLE
javax.xml.bind.DatatypeConverter isn't available on Android

### ISSUE THREAD

**Issue by apkelly** [qaware/heimdall#4]
Hi,

I'm trying to use the library in an Android project but the javax.xml.bind.DatatypeConverter class isn't available on Android. Is there any chance you can tweak the dependancies to use either the Base64 class supplied by Android or make a dependancy on commons-codec.

Thanks,

Andy.

**Comment by phxql** [comment]
Just added dependency to commons-codec. Next released version is compatible with Android.

**Comment by phxql** [comment]
Version 1.4 should be Android compatible.
